draft_journal_entry.txt:
	touch draft_journal_entry.txt
		touch draft_journal_entry.txt
			touch draft_journal_entry.txt
				touch draft_journal_entr.txt
					smell draft_journal_entry.txt
read.txt:toc.txt
	echo "This journal contains the following number of entries:" > read.txt
	wc -1 toc.txt | egrep -o "[0-9]+" >> read.txt
